# YAPI 工具配置文件示例
# 将此文件重命名为 yapi.yaml 并修改相应的配置值

# 配置说明:
# 1. base_url 和 token 是必需配置项
# 2. 环境变量优先级高于配置文件，例如:
#    - YAPI_BASE_URL 会覆盖 base_url
#    - YAPI_TOKEN 会覆盖 token
# 3. 支持的配置文件位置:
#    - ./yapi.yaml (当前目录)
#    - ../../config/yapi.yaml
#    - ../../configs/yapi.yaml
#    - ~/.yapi/yapi.yaml (用户主目录)
#    - /etc/yapi/yapi.yaml (系统配置) 

# 基本配置 (必需)
base_url: "http://your-yapi-server.com"  # YAPI 服务器地址
token: "your_access_token"               # YAPI 项目访问令牌

# HTTP 客户端配置
timeout: 30          # 请求超时时间（秒）
retry_count: 3       # 重试次数