# 基本配置 (必需)
base_url: "http://yapi.xesv5.com"                                         # YAPI 服务器地址
token: "55dc4b9c00d0b4e84512c976b7471e9f66b12d5b5531f0eccf93b67668d94d59" # YAPI 项目访问令牌

# HTTP 客户端配置
timeout: 30          # 请求超时时间（秒）
retry_count: 3       # 重试次数
